### ISSUE TITLE
put notes to reference/cite the paper on nhaneA readme or vignettes?

### ISSUE THREAD

**Issue by ainilaha** [ainilaha/RNhanes#6]

**Comment by cjendres1** [comment]
Will definitely add this paper as the official nhanesA reference. 

Here's a conference proceeding that we should consider adding to our manuscript:
Towards Machine-Assisted Biomedical Data Preparation https://ceur-ws.org/Vol-3466/paper2.pdf

**Comment by ainilaha** [comment]
I have put the above conference proceeding paper to our manuscript along with the other papers you listed. @cjendres1
